### ISSUE TITLE
won't open

### ISSUE THREAD

**Issue by senolfndk** [zt64/Hyperion#22] opened 2022-08-13 17:33 UTC
not working

**Comment by zt64** [comment] 2022-08-13 18:19
Could you post the crash, it should be in logcat. I can't do much without it

**Comment by senolfndk** [comment] 2022-08-13 18:30
> Kazayı gönderebilir misiniz, logcat'te olmalı. onsuz pek yapamam

I don't know how to do it

**Comment by senolfndk** [comment] 2022-08-13 18:32
https://user-images.githubusercontent.com/52818836/184506438-5d95588a-8056-4b7b-b8e7-5bd6194b94f2.mp4

**Comment by zt64** [comment] 2022-08-13 18:38
You will need:
- A computer
- ADB installed (<https://streamable.com/h0618w>)
- An unix shell (windows users: use Git Bash or WSL)

1. Enable USB debugging in your phone's developer options
2. Run the following command in a terminal:
```sh
adb logcat -c
```
3. If you have not previously authorized adb on your phone, open it now and authorize your pc
4. Now open OpenCord and reproduce the issue
5. Run the following command again
```sh
adb logcat -d > logcat.txt
```
6. The generated logcat will be in your user home directory

**Comment by daBroma** [comment] 2022-08-13 18:39
Tried using without the VPN/Adblocker? Also try https://github.com/wingio/Logra or just simple `adb logcat`.

**Comment by senolfndk** [comment] 2022-08-13 18:44
> VPN/Adblocker olmadan kullanmayı denediniz mi? Ayrıca https://github.com/wingio/Logra veya sadece basit `adb logcat`.
i tried it doesn't work

**Comment by daBroma** [comment] 2022-08-13 18:46
Logra does not work? `adb logcat` does not work? Care to elaborate?

**Comment by wingio** [comment] 2022-08-13 18:48
logra needs special permission to read logs from other apps

**Comment by daBroma** [comment] 2022-08-13 18:49
Shizuku though?

**Comment by wingio** [comment] 2022-08-13 18:49
doubt they have shizuku installed and set up

**Comment by daBroma** [comment] 2022-08-13 18:50
Should be easier to setup than `adb shell` on their computer? Since it is a basic app that can use wireless debugging to get `adb shell` permissions?

**Comment by wingio** [comment] 2022-08-13 18:52
logra also doesn't have exporting yet

**Comment by DiamondMiner88** [comment] 2022-08-14 01:19
literally just follow what zt said i wrote that for a reason guhhhh

**Closed** 2022-08-16 10:57 UTC
